"""Generate requirements/SpeedReader_v2_Traceability_Report.md.

Statuses are deliberately conservative. "DOMAIN PASS" means: implemented as a pure domain module, covered by
passing unit tests, and exercised live on /frozen-v2-demo. It does NOT mean production PASS - the v2.0 document
reserves certification for a separate independent QA job (AC-C10).
"""
import glob
import os
import re

TESTS = glob.glob("hosted-app/tests/unit/v2/*.test.ts")


def tests_for(prefix):
    return sorted(os.path.basename(t) for t in TESTS if os.path.basename(t).startswith(prefix))


FR = [
    ("FR-001", "Five content-difficulty Worlds", "worlds.ts"),
    ("FR-002", "World 2+ direction", "world-strategies.ts"),
    ("FR-003", "1,500 canonical passages", "catalog.ts"),
    ("FR-004", "First 150 passages", "foundation.ts"),
    ("FR-005", "Stamina staircase", "stamina.ts"),
    ("FR-006", "Stamina transition precedence", "stamina-transition.ts, learner-aggregate.ts"),
    ("FR-007", "AC-53 replacement (AC-53R)", "ac53r.ts"),
    ("FR-008", "Ten-minute initial assessment", "initial-assessment.ts"),
    ("FR-009", "Personal trajectory", "personal-trajectory.ts"),
    ("FR-010", "World 1 speed ceiling", "speed-ceiling.ts"),
    ("FR-011", "Level semantics", "level-semantics.ts"),
    ("FR-012", "Comprehension is the only WPM gate", "gate-evidence.ts"),
    ("FR-013", "Passage GREEN threshold", "comprehension-threshold.ts"),
    ("FR-014", "First-five rule", "first-five.ts, core-wpm.ts"),
    ("FR-015", "Post-five rule", "core-wpm.ts"),
    ("FR-016", "Earned WPM is never removed", "no-decrement.ts"),
    ("FR-017", "New passages prove progress", "attempt-types.ts"),
    ("FR-018", "Familiar-practice behaviour", "familiar-practice.ts"),
    ("FR-019", "Support is invisible", "learner-language.ts"),
    ("FR-020", "Hybrid evidence model", "comprehension-score.ts, calibration.ts"),
    ("FR-021", "Weighting lifecycle", "calibration-lifecycle.ts"),
    ("FR-022", "Structured question alignment", "question-alignment.ts"),
    ("FR-023", "Spoken comprehension expression", "spoken-expression.ts"),
    ("FR-024", "ASR uncertainty", "spoken-evidence.ts"),
    ("FR-025", "BPC after every passage", "best-comprehension.ts"),
    ("FR-026", "BPC story-style", "bpc-style.ts"),
    ("FR-027", "BPC fidelity", "bpc-fidelity.ts"),
    ("FR-028", "Permanent cross-World feature", "expression-by-world.ts"),
    ("FR-029", "Numeric comprehension is private", "learner-feedback.ts"),
    ("FR-030", ">=75% is a celebration", "passage-completion.ts"),
    ("FR-031", "Below 75% remains positive", "passage-completion.ts"),
    ("FR-032", "Level-Up celebration", "learner-feedback.ts, passage-completion.ts"),
    ("FR-033", "Book-time impact", "book-time.ts"),
    ("FR-034", "News Reader parallel track", "news-reader.ts"),
    ("FR-035", "Independence from core progression", "learner-aggregate.ts"),
    ("FR-036", "Shared content, separate state", "evidence-store.ts"),
    ("FR-037", "Reference delivery", "reference-audio.ts"),
    ("FR-038", "Oral two-read coaching", "news-reader-coaching.ts"),
    ("FR-039", "Oral-as-core-gate superseded", "supersession.ts"),
    ("FR-040", "Passage 1500 not sufficient", "world1-completion.ts"),
    ("FR-041", "150 WPM not mandatory", "world1-completion.ts"),
    ("FR-042", "Level Ups do not substitute readiness", "world1-completion.ts"),
    ("FR-043", "News Reader does not block progression", "world1-completion.ts"),
    ("FR-044", "Readiness-critical forms", "readiness-forms.ts"),
    ("FR-045", "Evidence recency", "evidence-recency.ts"),
    ("FR-046", "Threshold lifecycle", "threshold-lifecycle.ts"),
    ("FR-047", "Attempt types and records", "attempt-types.ts, attempt-record.ts"),
    ("FR-048", "Evidence separation", "evidence-governance.ts"),
    ("FR-049", "Explainability", "explainability.ts"),
]

out = []
w = out.append
w("# SpeedReader v2.0 - Implementation traceability report")
w("")
w("Source of truth: `requirements/SpeedReader_Final_Frozen_Requirements_Codex_Acceptance_v2.0.md`.")
w("Generated by `tools/gen-traceability.py` from the repository state. **This report does not claim production PASS**: per")
w("AC-C10 and section 20, only a separate independent QA job may certify. It records what exists, what is verified")
w("and, just as importantly, what is NOT done.")
w("")
w("## How to read the statuses")
w("")
w("| Status | Meaning |")
w("|---|---|")
w("| **DOMAIN PASS** | Implemented as a pure, deterministic domain module; covered by passing unit tests; exercised live on `/frozen-v2-demo` (speedreader.babystepsindia.com). Not yet wired into the learner screens. |")
w("| **PARTIAL** | Some of the requirement is implemented and verified; the rest is listed in the note. |")
w("| **NOT DONE** | Not implemented or verifiably failing today. |")
w("| **PENDING INDEPENDENT QA** | Cannot be satisfied by code alone; needs the independent QA process. |")
w("")
w("## Headline gaps (read first)")
w("")
w("1. **The v2 engine is not wired into the learner experience.** The shipped learner screens are still the older")
w("   36-level demo (`hosted-app/ui/page.tsx`, `ui/components/*`). The v2 modules in `hosted-app/lib/v2/` are verified in")
w("   isolation and on the `/frozen-v2-demo` verification page, not driving the real game. AC-P01, AC-P11, AC-P13, AC-P29")
w("   are therefore not satisfied for what a child actually sees.")
w("2. **AC-P29 currently FAILS on the shipped UI.** A scan of `hosted-app/ui` with the new learner-language gate finds")
w("   `PASS`/`FAIL`/`remediation`/internal identifiers on the public `/…-demo` harness pages and \"pass the comprehension")
w("   check\" in the main page intro. The harness pages are internal diagnostics but are publicly routable.")
w("3. **Required content does not exist in the repository**: 1,500 canonical passages (the demo file has six, of 71-79 words;")
w("   none is the required 100), QA-approved Best Possible Comprehension texts, approved equivalent readiness forms,")
w("   canonical reference audio. The domain code validates and gates all of these; nothing supplies them yet.")
w("3b. **No ASR/audio capture, no server persistence, no News Reader UI.** Spoken evidence, the progress store and the")
w("   News Reader are modelled and tested as domain logic only (`ProgressStore` is an in-memory transactional model).")
w("4. **Approved Knowledge Map ACs cannot be verified here.** The v2.0 document requires \"all applicable approved Knowledge")
w("   Map ACs pass\"; the KM acceptance package is not in this repository. Only the KM coordinate semantics")
w("   (15 RS x 10 P, 15 strands) are retained and tested (`world1-framework.test.ts`).")
w("5. **PROVISIONAL_PILOT values are placeholders** (70/30 weights, assessment search parameters, ASR confidence 0.6,")
w("   recency 180 days / 120 sessions, spoken-expression component weights). They are versioned and registered in")
w("   `threshold-lifecycle.ts` but need real calibration.")
w("")

w("## Functional requirements FR-001 .. FR-049")
w("")
w("| Requirement | Title | Module(s) in `hosted-app/lib/v2/` | Unit tests | Status | Note |")
w("|---|---|---|---|---|---|")
NOTES = {
    "FR-006": "Enforced in the aggregate; no learner UI.",
    "FR-008": "Engine only; the ten-minute assessment screen is not built.",
    "FR-019": "Copy + language gate only; shipped screens not migrated (see headline gap 2).",
    "FR-023": "Deterministic idea-matching evaluator over authored idea definitions; no authored ideas exist for the 1,500 passages and no audio capture.",
    "FR-024": "Policy + audit modelled; no real ASR provider integrated.",
    "FR-025": "Gate and lifecycle only; no approved BPC content.",
    "FR-026": "Structural lint only - semantic quality (AC-P17) needs independent QA.",
    "FR-027": "Mechanical grounding check only - semantic fidelity needs independent QA.",
    "FR-029": "Builder + leak scanner; shipped screens not migrated.",
    "FR-030": "Domain pipeline; no UI.",
    "FR-031": "Domain pipeline; no UI.",
    "FR-032": "Domain feedback object; no animation/UI.",
    "FR-033": "Domain message; no UI.",
    "FR-034": "State namespace and metrics only; no recording UI.",
    "FR-037": "Validation and platform-independent resolution only; no reference audio assets exist.",
    "FR-038": "Coaching calculation only; no recording UI.",
    "FR-040": "Readiness requirement modelled as the 15 RS competencies confirmed on approved forms (an interpretation; the exact readiness definition lives in the KM package, which is not in the repo).",
    "FR-044": "Validation/selection logic only; no approved forms exist.",
    "FR-045": "Placeholder thresholds.",
}
for fr, title, mods in FR:
    prefix = fr.lower() + "-"
    tests = tests_for(prefix)
    status = "PARTIAL" if fr in NOTES else "DOMAIN PASS"
    w("| %s | %s | %s | %s | %s | %s |" % (fr, title, mods, ", ".join("`%s`" % t for t in tests) or "-", status, NOTES.get(fr, "")))
w("")

w("## Codex implementation instructions")
w("")
w("| Instruction | Status | Evidence / note |")
w("|---|---|---|")
w("| CODEX-01 Do not redesign | DOMAIN PASS | Stale-rule scan (AC-C01); supersession register; no invented World/Level model. |")
w("| CODEX-02 Separate domain state machines | PARTIAL | Separate modules/state for assessment, core WPM, canonical sequence, scoring, familiar practice, BPC, News Reader and calibration; readiness is modelled (`world1-completion.ts`, `readiness-forms.ts`, `evidence-recency.ts`). No generic score/level field. |")
w("| CODEX-03 Core WPM state machine | DOMAIN PASS | `core-wpm.ts`. Documented assumption: the post-five streak counts passages 6+ only (FR-015 wording); CODEX-03 pseudocode could be read as also counting passages 4-5. |")
w("| CODEX-04 Stamina collision rule | DOMAIN PASS | `stamina-transition.ts`, `learner-aggregate.ts`, `explainability.ts`. |")
w("| CODEX-05 Practice selection | DOMAIN PASS | `familiar-practice.ts`. |")
w("| CODEX-06 Comprehension scoring | DOMAIN PASS | `comprehension-score.ts`; 70/30 only in `calibration.ts`. |")
w("| CODEX-07 Spoken-expression evaluator | PARTIAL | `spoken-expression.ts`, `spoken-evidence.ts` - returns score/components, coverage, uncertainty, coaching. Authored idea data and ASR integration are missing. |")
w("| CODEX-08 BPC generator | PARTIAL | Delivery gate, style lint and fidelity check exist; per the instruction, production should use pre-generated QA-approved text, which does not exist yet. |")
w("| CODEX-09 Learner-facing feedback contract | PARTIAL | `learner-feedback.ts`, `learner-language.ts`; not applied to the shipped screens. |")
w("| CODEX-10 News Reader isolation | DOMAIN PASS | `news-reader.ts` imports nothing from core; FR-035 property tests. |")
w("| CODEX-11 Version everything | PARTIAL | Every attempt record stores six rule versions (`attempt-record.ts`); decision replay uses the ledger. Tokenizer/content/readiness versions are placeholder strings until real versioned sources exist. |")
w("| CODEX-12 Fail safe | DOMAIN PASS | Technical uncertainty yields no score, no evidence, no Level Up, no penalty (FR-024, FR-048 tests, B11). |")
w("")

AC_P = [
    ("AC-P01", "Ten-minute baseline", "PARTIAL", "FR-008 engine verified (bounded, stored baseline, P1 at that WPM, no age/peer/News Reader input). Assessment screen not built."),
    ("AC-P02", "Personal progression", "DOMAIN PASS", "FR-009 + FR-035 tests: different starting WPMs, same canonical sequence."),
    ("AC-P03", "150 WPM ceiling", "DOMAIN PASS", "FR-010; B07/B08."),
    ("AC-P04", "First-five 4/5", "DOMAIN PASS", "FR-014; B03."),
    ("AC-P05", "First-five 3/5", "DOMAIN PASS", "FR-014; B04."),
    ("AC-P06", "Three consecutive post-five", "DOMAIN PASS", "FR-015; B05."),
    ("AC-P07", "Streak reset", "DOMAIN PASS", "FR-015; B06."),
    ("AC-P08", "No decrement", "DOMAIN PASS", "FR-016 exhaustive over all 2^14 sequences."),
    ("AC-P09", "Familiar practice exclusion", "DOMAIN PASS", "FR-017/FR-018; B10."),
    ("AC-P10", "Familiar practice speed", "DOMAIN PASS", "FR-018: served at the current earned WPM."),
    ("AC-P11", "Invisible support", "PARTIAL", "FR-019 copy verified; no learner screen implements practice yet."),
    ("AC-P12", "Hybrid comprehension", "DOMAIN PASS", "FR-020: separate stored components, one auditable result."),
    ("AC-P13", "75% privacy", "PARTIAL", "FR-029 builder/scanner verified; shipped screens are legacy (see AC-P29)."),
    ("AC-P14", "Spoken expression meaningful", "DOMAIN PASS", "FR-021: spoken weight floor enforced."),
    ("AC-P15", "ASR fairness", "DOMAIN PASS", "FR-024; B11."),
    ("AC-P16", "BPC ordering", "DOMAIN PASS", "FR-025."),
    ("AC-P17", "BPC quality", "PENDING INDEPENDENT QA", "Only mechanical lint/grounding exists (FR-026/027); semantic quality needs independent QA on real content."),
    ("AC-P18", "Every passage has BPC", "PARTIAL", "Availability logic verified for GREEN/NOT_GREEN/unresolved; no BPC content exists."),
    ("AC-P19", "Level-Up semantics", "DOMAIN PASS", "FR-011."),
    ("AC-P20", "Level-Up book time", "DOMAIN PASS", "FR-033."),
    ("AC-P21", "Stamina staircase", "DOMAIN PASS", "FR-005: all 1,500 IDs; P1500 = 1,000 words."),
    ("AC-P22", "No double jump", "DOMAIN PASS", "FR-006; B09; every boundary property test."),
    ("AC-P23", "News Reader isolation", "DOMAIN PASS", "FR-035."),
    ("AC-P24", "News Reader parallel metrics", "PARTIAL", "FR-034/036/038 state + coaching verified; no recording UI."),
    ("AC-P25", "World completion below 150", "DOMAIN PASS", "FR-041 fixture."),
    ("AC-P26", "Passage count alone insufficient", "DOMAIN PASS", "FR-040."),
    ("AC-P27", "Approved reassessment forms", "DOMAIN PASS", "FR-044; B13. No approved forms exist yet."),
    ("AC-P28", "Auditability", "DOMAIN PASS", "FR-049 replay from the immutable ledger."),
    ("AC-P29", "Confidence-first language", "NOT DONE", "Zero negative labels in v2 modules, but the shipped legacy UI/harness pages fail the scan (headline gap 2)."),
    ("AC-P30", "Cross-platform consistency", "PARTIAL", "Decisions are pure domain functions (identical for identical evidence) and reference audio is a single canonical asset (FR-037); there is no server API yet."),
]
w("## Acceptance criteria - product behaviour (AC-P01 .. AC-P30)")
w("")
w("| AC | Title | Status | Evidence / note |")
w("|---|---|---|---|")
for ac in AC_P:
    w("| %s | %s | %s | %s |" % ac)
w("")

AC_C = [
    ("AC-C01", "No stale-rule implementation", "DOMAIN PASS", "`stale-rules.ts` scanner + `ac-c01-stale-rules.test.ts`; superseded v1 modules archived under `hosted-app/archive/` and excluded from build/tests."),
    ("AC-C02", "Explicit attempt type", "DOMAIN PASS", "FR-017/FR-047 validation rejects null/unknown types."),
    ("AC-C03", "Separate state", "DOMAIN PASS", "`ac-c03-separate-state.test.ts`: one field per domain, no generic score/level/status field, separate evidence namespaces."),
    ("AC-C04", "Idempotent progression", "DOMAIN PASS", "FR-047 idempotency tests; `applyNewPassage`."),
    ("AC-C05", "Transaction safety", "PARTIAL", "`progress-store.ts` proves atomic commit/rollback in an in-memory model; no real database transaction."),
    ("AC-C06", "Boundary tests", "DOMAIN PASS", "`boundary-matrix.ts` - 13/13 scenarios."),
    ("AC-C07", "Configuration governance", "PARTIAL", "`threshold-lifecycle.ts` registry + versions on attempts; some constants (e.g. spoken-expression weights) are versioned configs but not yet in the registry."),
    ("AC-C08", "Observability", "DOMAIN PASS", "`ops-log.ts`; ops events never reach learner views."),
    ("AC-C09", "Deterministic decision service", "DOMAIN PASS", "Determinism tests across engine, explainability and scoring modules."),
    ("AC-C10", "Independent QA gate", "PENDING INDEPENDENT QA", "Self-validation only. Not production-approved."),
]
w("## Acceptance criteria - Codex engineering gate (AC-C01 .. AC-C10)")
w("")
w("| AC | Title | Status | Evidence / note |")
w("|---|---|---|---|")
for ac in AC_C:
    w("| %s | %s | %s | %s |" % ac)
w("")
w("## Stale-rule scan (handoff item 4)")
w("")
w("`hosted-app/tests/unit/v2/ac-c01-stale-rules.test.ts` scans `hosted-app/lib`, `hosted-app/ui`, `container` and `app`")
w("for seven superseded behaviours and finds none. The scanner is itself proven to detect each (`stale-rules-fixtures.ts`).")
w("Removed from the active tree (archived, history in git): the v1 \"Decisions workbook\" product layer that implemented")
w("two-green-light gating (comprehension AND oral), three-session speed levels and age-band libraries.")
w("")
w("## Definition of done (section 20) - honest status")
w("")
w("| # | Item | Status |")
w("|---|---|---|")
w("| 1 | All FROZEN requirements implemented | Domain logic yes; learner-facing integration and content no |")
w("| 2 | Applicable approved KM ACs pass | Cannot verify - KM package not in repo |")
w("| 3 | Superseded behaviours absent | Yes (AC-C01), for the active tree |")
w("| 4 | PROVISIONAL_PILOT values versioned/configurable | Yes (placeholders) |")
w("| 5 | Structural and boundary tests pass | Yes |")
w("| 6 | Learner-facing confidence rules pass UX/content QA | No - legacy screens fail AC-P29 |")
w("| 7 | Deterministic and auditable decisions | Yes |")
w("| 8 | News Reader demonstrably isolated | Yes |")
w("| 9 | Familiar practice excluded from progression | Yes |")
w("| 10 | BPC delivered after scoring and passes fidelity QA | Delivery gate yes; fidelity QA pending |")
w("| 11 | Developer self-validation complete | Domain layer yes; integration no |")
w("| 12 | Independent QA certification | Not started |")
w("")
w("**Not production-ready. Do not treat any row above as certification.**")

with open("requirements/SpeedReader_v2_Traceability_Report.md", "w", encoding="utf8", newline="\n") as f:
    f.write("\n".join(out) + "\n")
print("rows:", len(FR), "FR;", len(AC_P), "AC-P;", len(AC_C), "AC-C")
